### ISSUE TITLE
nsp complains about jscs dependency security vulnerabilities

### ISSUE THREAD

**Issue by dhwang** [villadora/express-http-proxy#105]
My project is using nsp and getting this complaint. Is jscs needed other than devDependencies?

[11:37:10] (+) 1 vulnerabilities found
│               
│ Regular Expression Denial of Service                                                                                                                                   │ Name          │ minimatch                                                                                                                                                              │
│ Installed     │ 2.0.10  
│ Vulnerable    │ <=3.0.1                                                                                                                                                                │
│ Patched       │ >=3.0.2                                                                                                                                                                │
│ Path          │  express-http-proxy@0.7.3 > jscs@3.0.6 > vow-fs@0.3.5 > glob@4.5.3 > minimatch@2.0.10                                                      
│
│ More Info     │ https://nodesecurity.io/advisories/118

**Comment by monkpow** [comment]
Thanks.    3d8560c

**Comment by monkpow** [comment]
published 0.7.4 with this issue corrected.  Thanks for bringing it up.
