### ISSUE TITLE
Access to reponse headers

### ISSUE THREAD

**Issue by ashubham** [villadora/express-http-proxy#11]
Hello villadora,

How can I get access to the response headers of the response sent by the target server. I need to authenticate the response from the target based on response headers. Can we change the code to something like:

```
 if (intercept) {
            intercept(rsp, rspData, req, res, function(err, rspd, sent) {
              if (err) {
```

This will mimic the `request` modules callback signature too, which is `request(requestOpts, function (err, response, body)`

**Comment by topheman** [comment]
Hello @villadora, hello @ashubham ,

I have the same kind of request : I need to access the response headers sent by the target server to remove some of them before sending the response.

@ashubham I saw your fork, it seems that it should work out, shouldn't it ?

**Comment by benel** [comment]
@ashubham I saw that your commit (4d74e3253fa7f914c865ed1b24d364a23277463e) has been merged.
Does it make possible to modify the headers that will be sent (aka 'decorate the response headers')?

**Comment by benel** [comment]
For reference, here is the answer to my question:

```js
function(responseIn, data, req, responseOut, callback) {
  responseOut.set('Content-Type', responseIn.headers['content-type']);
  callback(null, data);
}
```
will for example change the case of reponse's `content-type` header into `Content-Type`.

**Comment by jbender** [comment]
@benel Does the above work as expected for you? I'm trying to set CORS headers, using something similar:

    intercept: function(rsp, data, req, res, callback) {
      res.set('Access-Control-Allow-Origin', 'localhost');
      callback(null, data.toString('utf8'));
    }

However, when the request actually comes back the headers are lower case (and it obviously doesn't work)

    Accept-Ranges: none
    Alternate-Protocol: 80:quic,p=0
    Cache-Control: private
    Connection: close
    Content-Length: 5069
    Content-Type: text/html; charset=utf-8
    Date: Sun, 05 Jul 2015 00:12:58 GMT
    Etag: W/"13cd-RuAJXsvEm59Hi0hsLqjfMQ"
    Server: Google Frontend
    Vary: Accept-Encoding
    X-Powered-By: Express
    access-control-allow-origin: localhost

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:9000/proxied-request. (Reason: CORS header 'Access-Control-Allow-Origin' does not match 'localhost').

**Comment by benel** [comment]
> headers are lower case (and it obviously doesn't work)

@jbender With every browser?

**Comment by jbender** [comment]
@benel Chrome, Safari, and Firefox all give this error.

**Comment by monkpow** [comment]
Closing this ticket.  It appears the first half has been resolved.

@jbender  and @benel, http specification says headers are case-insensitive;  I'm not going to try to fix this, but if you'd like to have a discussion about better support for the CORS use case, I'm open to that.

Regards.

**Comment by luciomartinez** [comment]
How to set CORS:

    app.use('/', proxy('www.target.domain', {
        userResHeaderDecorator: () => ({'Access-Control-Allow-Origin': '*'})
    });

Just leaving this here in case someone else enters into this ticket wondering how to do it.

**Comment by castrix** [comment]
adding to the comment from @luciomartinez , if you use `withCredentials` on the client, you need to set CORS whitelist like this:

```
const whitelist = ['http://localhost:3000', 'http://localhost:3003', 'http://localhost:3005']
app.use('/', proxy('www.target.domain', {
    userResHeaderDecorator: (headers) => {
    headers['access-control-allow-origin'] = whitelist.includes(req.headers.origin) ? req.headers.origin : '*'
    return headers
  }})
});
```
