### ISSUE TITLE
question: proxying a multipart request changes file byte array data

### ISSUE THREAD

**Issue by aminmeyghani** [villadora/express-http-proxy#112]
Hi, I am trying to proxy a multipart file request to my Java Spring server but for some reason the file bytes that Spring receives is not the same as the file that was uploaded. For example, a file whose byte array length is 3000 is transformed to about 6000. Any ideas why that's happening ?

This is the snippet that does proxies the request:

```javascript
  var apiProxy = proxy('http://localhost:8080', {
      forwardPath: function (req, res) {
          return '/api/v2/photos/upload';
      }
  });

  app.all("/api/upload", apiProxy);
```

**Comment by monkpow** [comment]
Try setting reqBodyEncoding to ```null```.   It may be that your request body is being re-encoded as utf-8 (the default encoding for requests in this library.

If this is not the issue, please let me know as many details as possible and I can dig in further. 

Thanks

**Comment by aminmeyghani** [comment]
Yup, that fixed it. Thanks!

**Comment by monkpow** [comment]
@aminmeyghani no problem.
