### ISSUE TITLE
decorateRequest example gives errors

### ISSUE THREAD

**Issue by sagarmah** [villadora/express-http-proxy#118]
I am trying to run the following example from the docs and would like to modify it to reach to one of my Web applications. But this gives me errors like wrap not defined and if I remove wrap, it says 
TypeError: Cannot read property 'length' of undefined. I know I am missing something, I am new to Nodejs and Express but any help will be great.
```
//Example code
app.use('/proxy', proxy('www.google.com', {
  decorateRequest: function(reqOpt, req) {
    reqOpt.headers['Content-Type'] = '';
    reqOpt.method = 'GET';
    reqOpt.bodyContent = wrap(req.bodyContent);
    return reqOpt;
  }
}));
```
Also my use case is to reach to 'https://localhost:3000/api/user' and add header as 
`reqOpt.headers['X-WEBAUTH-USER'] = 'test';`
so I can reach to my local app bypassing the login page for user 'test'. Am I on the right track to use the decorateRequest function for this?

**Comment by monkpow** [comment]
You are on the right track.    The example is probably poorly written;  ```wrap``` in this case is an example function, and doesn't exist as part of this library.   I think the intention was just to show that you could operate on the bodyContent.    I'll update the example for future readers.

in your case, I think you should be good with

```
```
  decorateRequest: function(reqOpt, req) {
    reqOpt.headers['X-WEBAUTH-USER'] = 'test';
    return reqOpt;
  }
```

Good luck.

**Comment by sagarmah** [comment]
thanks for the quick reply, this will work with https://localhost.. too right? or do I need to add something else?

**Comment by monkpow** [comment]
The library uses https for the proxy request when the path is https, so in many cases it will work out of the box.   If your https presents challenges (requires auth headers for instance), you'll need to address this in decorateRequest.

**Comment by sagarmah** [comment]
Thanks. I am closing the issue with this one. Its been a great help.

**Comment by sagarmah** [comment]
Hello I tried your suggestion and it sortof works. When I do the following on a server running at localhost:8000:
`app.use('/grafana', proxy('http://localhost:3000/', {
    decorateRequest: function(reqOpt, req) {
        reqOpt.headers['X-WEBAUTH-USER'] = 'user';
        return reqOpt;
    }
}));`
It returns a HTML page and tries to render it, but the browser is unable to find a lot of resources.
For instance the css has a relative path '/public/views/css/' in the html and it tries to search for the css at 'http://localhost:8000/public/views/css'
While it should actually find it at 'http://localhost:3000/public/views/css'.

Any pointers on how to resolve that?
