### ISSUE TITLE
odd behaviour on ECONNRESET

### ISSUE THREAD

**Issue by domasx2** [villadora/express-http-proxy#124]
Hi,

If request fails with ECONNRESET, it writes to response but also proceeds to next route by calling next().
This usually results with next route trying to send another esponse and producing a "headers already sent" error.
Why is this so? I think it would make more sense to not call next() after response has already been sent

see
https://github.com/villadora/express-http-proxy/blob/master/index.js#L161

**Comment by monkpow** [comment]
Yep, agree.  This is errant behavior.  I'll pick this up shortly.
