### ISSUE TITLE
rewrite path before sending the request

### ISSUE THREAD

**Issue by sagarmah** [villadora/express-http-proxy#125]
I have a nodejs app running at localhost:4000 From here I want to proxy to localhost:15672 and authorize the user directly to his homepage. so localhost:4000/manage should show the response from localhost:15672/#/login/user/password

A simple app.get does work, but the URL contains credentials in pathname and so want to find an internal way to use it somehow. I am using express-http-proxy library already, but dont understand how to change pathname before sending the request. I have been stuck way too long, so a quick help will be greatly appreciated.

I have tried this but does not work:

`app.use('/manage', ensureAuthenticated, proxy('http://localhost:15672', {
    decorateRequest: function(reqOpt){
            reqOpt.hostname = 'localhost:15672';
            reqOpt.path = '/manage/#/login/user/password';
            return reqOpt;
    }

}))
app.listen(4000);`

**Comment by monkpow** [comment]
I think for this case, you will use ```forwardPath``` option, which allows you to modify the path to the proxy server.   Check that out in the documentation, and let me know if you have additional questions.
