### ISSUE TITLE
Chokes on trailing slash

### ISSUE THREAD

**Issue by SimplGy** [villadora/express-http-proxy#13]
I think it might choke in the case where there's a port with a trailing slash specified as `host`.

Eg:

    app.use(proxy('http://fantasticmango:4242/', options));

Throws:

    net.js:901
      throw new RangeError('port should be > 0 and < 65536: ' + port);
            ^
    RangeError: port should be > 0 and < 65536: 0
      at Socket.connect (net.js:901:13)
      at Agent.exports.connect.exports.createConnection (net.js:92:35)

This is a bummer because `url.parse()` puts a trailing slash in the `href` property. To do it manually and generically the user needs to use `hostname` and `port` joined by a `:`, but only when port is present. Easier to strip the tail slash off maybe.

Want a PR to fix this in the library, or am I missing something?

I am using app code like this to work around (CS sorry):

    if config.api.href[config.api.href.length - 1] is '/'
      safeHref = config.api.href.substr 0, config.api.href.length - 1
    app.use proxy safeHref, options

**Comment by villadora** [comment]
a PR is welcome, of cause! Or I may made the change when I'm free....
