### ISSUE TITLE
Possible to add query parameters to proxy request?

### ISSUE THREAD

**Issue by roger-panella** [villadora/express-http-proxy#131]
Is it possible to add a string of query parameters to the end of the path of the proxy request before sending?

I've tried adding ProxyReq.query in decorateRequest and formatting the parameters as a JSON object and also tried as a string, but doesn't look like decorateRequest handles query parameters that way.  

Just wanted to see if there was a way to do it.  Thanks!

Edit:  I ended up working it out by adding the query parameters to proxyReq.path in decorateRequest.

**Comment by monkpow** [comment]
You could use ```forwardPath``` to modify the path as well, fwiw.
