### ISSUE TITLE
Proxy works for GET but POST loses body

### ISSUE THREAD

**Issue by raddevon** [villadora/express-http-proxy#138]
I have configured a proxy that works perfectly for GET requests, but the request JSON body doesn't get through on POST requests.

```javascript
app.use('/cart', proxy(GS_API_URL, {
  reqAsBuffer: true,
  reqBodyEncoding: null,
  decorateRequest: function(proxyReq, originalReq) {
    proxyReq.headers = {
      'Authorization': 'Bearer ' + originalReq.session.gsApiToken
    };
    return proxyReq;
  },
  forwardPath: function(req) {
    return '/v1/cart' + req.path;
  },
  intercept: function(targetResponse, responseData, req, res, callback) {
    if (targetResponse.statusCode === 401) {
      req.session.destroy();
      return callback(new gsErrors.UnauthorizedError('API token rejected while fetching cart contents'));
    }
    return callback(null, responseData);
  }
}));
```

I recently added the `reqAsBuffer` and `reqBodyEncoding` options after seeing #114, but that doesn't seem to help. I have tried this with only `reqAsBuffer` set and without either of those two set. I do have body-parser running on this app, but that middleware is after the proxy.

At the destination server, I'm running body-parser on this request and it sets `req.body` to an empty object. I previously had this API running on the Express server where I'm currently building the proxy, so I'm certain the front-end is sending the body as intended. Can you see why I'm not able to get the JSON body through the proxy to my other Express server?

**UPDATE:** I should clarify that the GET request I have working through the proxy does not have a body. The problem might be that the body is not getting through regardless of the method.

**Comment by raddevon** [comment]
Found the answer. In setting the entire headers object of the proxy request with nothing but my auth header, the new request didn't have the content type it needed to be handled properly as JSON. I added the `Content-Type` header in `decorateRequest`, and all is good.

Here's what my `decorateRequest looks like now:

```javascript
  decorateRequest: function(proxyReq, originalReq) {
    proxyReq.headers = {
      'Authorization': 'Bearer ' + originalReq.session.gsApiToken,
      'Content-Type': 'application/json'
    };
    return proxyReq;
  },
```

**Comment by aguegu** [comment]
I stuck in the same problem. And it is weird.

```js
router.post('/', requestProxy({
  url: 'https://httpbin.org/post',
}));
```

does not work
