### ISSUE TITLE
Chunked Response

### ISSUE THREAD

**Issue by houzi-lim** [villadora/express-http-proxy#141]
Hi,

I am a beginner that have couple questions regarding this http proxy.
Say I use this as a proxy to a server that return large data in chunks.
1. Is it true that the proxy will always collect all the chunks before sending the full response back as a whole to the client regardless the optional intercept?
2. If so, doesn't that mean the responsiveness might not be good for the client?

Thanks in advance.

**Comment by monkpow** [comment]
@houzi-lim Yeah, this is the current behavior of the library, and yes, this means it might not be efficient for large responses.

There is currently a feature (intercept) that allows you to operate on the proxied response before sending it on that I believe drove that decision.

**Comment by houzi-lim** [comment]
@monkpow, thanks for the confirmation.
