### ISSUE TITLE
memoizeHost does not work

### ISSUE THREAD

**Issue by arjanfrans** [villadora/express-http-proxy#157]
I am trying to generate the proxy url dynamically by passing a function into the first argument. As an option I have `memoizeHost` set to `false`. I used the example coin toss function, but it always results in the same outcome.

**Comment by monkpow** [comment]
@arjanfrans Feel free to show your code.  It appears to work for me, but you might have a use case I haven't seen yet.

**Comment by arjanfrans** [comment]
Unfortunately I do not have access to the code I used anymore. I just tried to reproduce it again, but it does seem to work fine.

I'll close this issue.
