### ISSUE TITLE
Can't console log within decorateRequest function

### ISSUE THREAD

**Issue by marr** [villadora/express-http-proxy#159]
I am trying to console.log out during the decorateRequest function and I am seeing nothing output in my console. I tried the debug module as well. Is there some way I could diagnose this?

Thanks

**Comment by marr** [comment]
not an issue

**Comment by reallyroy** [comment]
I'm having the same issue. Nothing I console on any option function seems to be printing. I want to  check the path of the incoming request and then modify it.

**Comment by reallyroy** [comment]
Hi Monkpow,

I figured out why this was happening. I was using the newer functions instead of the older ones. Hadn't realized that the notes were updated to 1.0 while the code was not at that time. Once I used the older functions it all worked fine.

Regards,
Roy

**Comment by monkpow** [comment]
Thanks for letting me know @reallyroy.  Sorry for the confusion I caused you.   I borked the transition between the old version and the new version, and it sounds like I caused many hours of debugging headaches for you and others.     Learning experience for me, and my apologies to you.
