### ISSUE TITLE
The data in req.body is mutated

### ISSUE THREAD

**Issue by denizozger** [villadora/express-http-proxy#162]
Where the application running in port `3000` forwards request body to `3001`;

```
curl -X POST -H "Content-Type: application/x-www-form-urlencoded" -H "Cache-Control: no-cache" -d 'phone=123123' "http://localhost:3000/"
```

the receiving end gets the body as:

```
{"{\"phone\":\"123123\"}":""}
```

**Comment by adamrisser** [comment]
I had the same problem when I was using body-parser in my app. I removed body-parser and it went away.

**Comment by cmal** [comment]
I had a similar problem but I am not sure it is the same.
I send a post request with "Content-Type: application/x-www-form-urlencoded", and param key value pairs. It shows right in browser but the server side get nil in the key's value. Can anyone give me some advice how to debug and solve this problem?

**Comment by cmal** [comment]
I moved the `proxy` to above `body-parser` in express and it works now. Thanks @adamrisser .

**Comment by marr** [comment]
This one got me too!

**Comment by fuquanlin** [comment]
I meet same problem. How should i fix it? or any work around solution

**Comment by denizozger** [comment]
Resolved with @adamrisser's suggestion, thanks.
