### ISSUE TITLE
Version Discrepancy - Release 0.7, NPM Package 0.11

### ISSUE THREAD

**Issue by SKHameed86** [villadora/express-http-proxy#163]
Working on a project recently updated by a colleague, after I had made an update.

Trying to npm install, but there's a discrepancy between the version numbers. Package.json refers to the latest version, 0.11, but the GitHub release is up to 0.7.

**Comment by monkpow** [comment]
@SKHameed86 I'm unclear on your question.  Can you say more please?

**Comment by pragmaticivan** [comment]
Found the same issue here. There's no release tag on Github to match the current latest one on npm (0.11). Looks like the releases on npm are not being published as new tags on Github.

**Comment by monkpow** [comment]
@SKHameed86 @pragmaticivan I think this was my issue; that I botched 0.11 when I published it.   I believe I've fixed it; could either of you confirm if you are still experiencing the issue?

Much appreciated.
