### ISSUE TITLE
documentation out-of-sync with currently published module (0.11.0) on npm  

### ISSUE THREAD

**Issue by GuentherFroestl** [villadora/express-http-proxy#218]
First of all many thx and kudos for such an useful middleware module for express.js. Exactly what I'm in need for.
Unfortunately the docu is ahead of the curently published version on npm and only one branch existing the'master'.
Would recommend to do such major refacoring next time within a own branch, leaving master untouched and in sysnc with the publishe version.
Never mind, really good stuff and the refactored version looks even nicer :-)

**Comment by Arthur-W-White** [comment]
Yes, took me awhile to figure this out... 
When you do:
npm install express-http-proxy --save
You get a version that is "outdated" and the docs' suggestions don't work.
For instance, `proxyReqPathResolver` doesn't work but `forwaredPath` does.
This may seem like a none-issue but it could cost unwary noob devs many hours of our lives.

Only figured this after reading some of the code inside node_modules and comparing it with the expected code from the repository.

Thanks for the useful module. It works perfectly.

**Comment by monkpow** [comment]
@GuentherFroestl @Arthur-W-White Thanks for the feedback;  I have published the 1.0.0 module now, so the documentation is up-to-date with code published on npm.

@GuentherFroestl I wanted to allow the lib to 'bake' on master;  letting early adopters grab it without disrupting those users currently using the published versions.   I'll look at other options to make this more clear to users in the future.

**Comment by GuentherFroestl** [comment]
@Arthur-W-White Thx a lot for the update . One approach which we are using here in  my project for early adopters is to use a branch like develop. You still could publish the new stuff to npm using a tag like 'next'. So your early adopters could pull it from with the 'next' tag.
In anyway realy good stuff your proxy, using it already in my project with success, so many thx :-)
