### ISSUE TITLE
DEPTH_ZERO_SELF_SIGNED_CERT error

### ISSUE THREAD

**Issue by halt-hammerzeit** [villadora/express-http-proxy#22]
Can be avoided by:

```
process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0" # Avoids DEPTH_ZERO_SELF_SIGNED_CERT error for self-signed certs
```

But maybe there is a better option.
I didn't find the option in your readme.

There is an option called rejectUnauthorized.
https://nodejs.org/api/tls.html

Seems that it's the option to look into:

```
var req = (ssl ? https : http).request({ rejectUnauthorized: false })
```

You'll have to make an opiton for this one

**Comment by yyscamper** [comment]
@halt-hammerzeit: 
I encountered same issue, I fixed it by adding the rejectUnauthorized option in decorateRequest:

app.use('/proxy', proxy('www.google.com', {
  forwardPath: function(req, res) {
    return require('url').parse(req.url).path;
  },
  decorateRequest: function(req) {
       * req.rejectUnauthorized=false; *
       return req;
  }
}));

**Comment by halt-hammerzeit** [comment]
Also recently I found out about Node.js TLS module `ca` option which takes your self-generated root CA and then this error goes away.
