### ISSUE TITLE
remote path not used

### ISSUE THREAD

**Issue by danosaure** [villadora/express-http-proxy#220]
Hi,

I'm wondering why the remote path is not considered?

    app.use('/somePath', proxy('http://other.server/other/path'));

So that when I call `/somePath/abc`, it is proxied to `http://other.server/other/path/abc`?

Right now, I have to workaround with something like:

    const proxyPath = url.parse('http://other.server/other/path').path;
    app.use('/somePath', proxy('http://other.server/other/path', {
        proxyReqPathResolver(req) {
            const reqPath = url.parse(req.url).path;
            return [proxyPath, reqPath].join('/');
        }
    }));

Thanks,

**Comment by monkpow** [comment]
I think you're asking:

When i provide a 'host' argument,  and i also include a path in the host argument, why does that path get discarded?

The library simply works differently;  in that it treats host and path as separate concerns.

IOW:  The process that parses the host argument will extract the host portion from whatever url (or string or function result) you provide.  It discards any path, query strings, or fragment identifiers, as it does not expect them.

If you'd like to modify the proxyPath, use ```proxyReqPathResolver``` (as you've done in your example)

In this case, you're pretty close to what I would do, although I might simplify it a bit

```
const proxyPath = '/other/path'
app.use('/somePath', proxy('http://other.server/other/path', {
    proxyReqPathResolver(req) {
        const reqPath = url.parse(req.url).path;
        return [proxyPath, reqPath].join('/');
    }
}));
```

HTH

**Comment by danosaure** [comment]
Hi,

Thanks for getting back.. I'm just using the full value because they come from a config file. I understand what you are saying, what I am suggesting is to make that available... It wasn't really clear to me it was only the host, not the proxy url.

In Apache, you would do this type of configuration

ProxyPass "/local/path" "http://remote.server/remote/path"

Thus my natural first instinct to put it that way.

I had to adjust that last item. These issues would be better handled if it was done by the proxy middleware.

```javascript
        proxyReqPathResolver(req) {
            let reqPath = url.parse(req.url).path;
            if (reqPath === '/') {
                return proxyPath;
            }
            return [proxyPath, reqPath].join('/');
        },
```

**Comment by monkpow** [comment]
Yep, I see why it would be helpful in your case.     My POV is I'm oriented toward having a single place to define and modify each of the workflow steps, as I think its confusing to authors to have multiple ways to mutate the path.

A simple example is:  What would you do if a user passed a path on the host argument, and also defined a pathResolver?   Do we ignore one value or the other, assume that they should be applied in a specific order, or ...?  

I'd be happy to look at a patch to enable this -- and perhaps change my mind -- but I'm currently happy with the clarity of having ```host``` represent the host value, and deferring path manipulation to the pathResolver function.

**Comment by danosaure** [comment]
I guess, my first reflex is not even thinking of needing a pathResolver for my default path:

```javascript
app.use('/hello', proxy('http://other.host/remote/path', {headers: {'X-Forwarded-Path': '/hello'}}));
```

because i would think that: /hello/my/friend would bring me to http://other.host/remote/path/my/friend.

I'm not saying it should be modified, just that was my first expectation... but I figure it would that I need to make more complicate configs for the "simple" use case.

In your approach, I would say, sending in the default path and return the mutated path.

```javascript
proxyReqPathResolver(req, defaultPath) {
  // defaultPath = /remote/path (in sample above).
}
```

again, I understand your way of thinking because you expected `proxy(hostname)`, not a `remote URL`...

Thanks for explaining.

**Comment by monkpow** [comment]
Happy about the conversation, thank you.    I'm going to close this, but feel free to re-open if you'd like to continue the conversation.
