### ISSUE TITLE
"limit" option no more taken into account

### ISSUE THREAD

**Issue by jacomyal** [villadora/express-http-proxy#228]
The "limit" option [is not dealt with](https://github.com/villadora/express-http-proxy/blob/f1a7e449bc8a737c29b0ac2407a9cb34c64664b5/lib/resolveOptions.js#L32-L46) in the `resolveOptions.js` file.

**Comment by monkpow** [comment]
Thank you for the report.  You are correct.   Fix should be posted today.

**Comment by jacomyal** [comment]
Nice, fixed already!
Thanks a lot for your reactivity :)
