### ISSUE TITLE
Invalid default proxy path

### ISSUE THREAD

**Issue by bitsal** [villadora/express-http-proxy#231]
Version `1.0.3`

When I configure the proxy with all default options I expect it proxies an origin request as is to the proxy.
```
var httpProxy = require('express-http-proxy');
...
devServer.use('/my/url', httpProxy(https://proxy-server.com/);
```

but it sends it to a root path `/` to the proxy server even 
```
proxyReqPathResolver: function(req) {
    console.log('proxyReqPathResolver: req.url -> ' + req.url); // -> '/'
    console.log('proxyReqPathResolver: req.originalUrl -> ' + req.originalUrl); // -> /my/url
    ...
},
```

Could you explain me if it works as designed and I have to override `proxyReqPathResolver` OR there is an issue?

**Comment by monkpow** [comment]
Hi @bitsal,  thanks for the ticket.

I feel like I'm not understanding your request enough to help.    It looks like either you misunderstand the API, or I misunderstand your issue.

I've added some tests to the suite to demonstrate how I expect/believe it to work, essentially:


Given:
```
app.use('/root/, proxy('http://proxy.com'))
````

a request to /root => http://proxy.com/
a request to /root/beer => http://proxy.com/beer
a request to /root/hog/or/die => http://proxy.com/hog/or/die

If you want to include the matching path token as well (in this case root), you will have to provide your own resolver, something like

```
proxyReqPathResolver: function (req) {
   return '/root/' + req.url;
})
```

Please let me know if this doesn't answer your question, or I can help more.   If you'd like to add a patch to preserve the matching token, I'd be happy to accept it.

Regards,
Nik

**Comment by bitsal** [comment]
@monkpow Thank you for the quick answer. It seems you are right and it works as you described. 

Should it be a default behavior or `/root` also gonna be included in the target proxy path?

**Comment by monkpow** [comment]
@bitsal The default behavior should remain the same as today, if nothing else, to ensure a consistent experience for those using it today.   I think you might want an option called ```preserveMatchingPath``` or something like that.      Remember that authors can over-ride the proxyReqPathResover, so you'll want to think through how your match affects authors who over-ride the resolver.

Thanks.

**Comment by bitsal** [comment]
Thanks!
