### ISSUE TITLE
Connection timeout

### ISSUE THREAD

**Issue by seeden** [villadora/express-http-proxy#24]
Can you add options for connection timeout?
request.socket.setTimeout(60000); // 60 sec

I can see a lot of errors:
Error: connect ETIMEDOUT
   at exports._errnoException (util.js:746:11)
   at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)

Thanks

**Comment by monkpow** [comment]
seems fairly easy and useful.   I'll look into this.

**Comment by seeden** [comment]
any update ?

**Comment by monkpow** [comment]
Hi @seeden.    In progress.  I expect to complete this week.

**Comment by monkpow** [comment]
Ha, took me a few pushes to get the commit correct, but its on the main line now.   HTH

**Comment by monkpow** [comment]
https://github.com/villadora/express-http-proxy#timeout
