### ISSUE TITLE
shasum check failed

### ISSUE THREAD

**Issue by perfectr** [villadora/express-http-proxy#240]
I'm getting a "shasum check failed" error when I try to download express-http-proxy from npm. I'm trying to use "Apimocker" but it has a dependency on express-http-proxy and whenever I do a npm install I get the following error;

```
$ npm install
npm ERR! fetch failed http://registry.npmjs.org/express-http-proxy/-/express-http-proxy-1.0.3.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 403
npm ERR! Darwin 16.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10

npm ERR! shasum check failed for /var/folders/yf/1qn0vncd1115qzc4my9p6_ndsr6ym3/T/npm-8186-9831bf41/registry.npmjs.org/express-http-proxy/-/express-http-proxy-1.0.3.tgz
npm ERR! Expected: 5876364c3824464d75f9a3ed09a62667f9d576a6
npm ERR! Actual:   38a0cb7059c747c7ccfe8d1ccbfa7e6eecfeaa48
npm ERR! From:     http://registry.npmjs.org/express-http-proxy/-/express-http-proxy-1.0.3.tgz
```

I can workaround the problem by separately importing version 0.7.0 of express-http-proxy into my package.json but would like to resolve this issue and remove the separate import if possible.

Digging into the downloaded archive it looks like a backup "bak.tar" has been accidentally left inside of the express-http-proxy.tgz file. Which may or may not be part of the problem.

**Comment by monkpow** [comment]
Thank you for this.   I have confirmed, and I will update npm shortly.

**Comment by monkpow** [comment]
@perfectr I've posted a new version to npm, and believe I've addressed it.   Would you let me know if you continue to have issues.

**Comment by perfectr** [comment]
@monkpow Great! -That seems to have fixed the problem. I can now download the 1.04 version and it doesn't have any npm related issues. Thanks!
