### ISSUE TITLE
Create new release for version 1.0.4

### ISSUE THREAD

**Issue by ufologby** [villadora/express-http-proxy#246]
Could you please create new release for version 1.0.4 that will be available on Releases page.
Problem that if i tried to install "express-http-proxy": "~1.0.4" error :

npm ERR! code ETARGET
 
npm ERR! notarget No compatible version found: express-http-proxy@'>=1.0.4 <1.1.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.0.1","0.1.0","0.1.1","0.2.0","0.2.1","0.2.2","0.3.0","0.3.1","0.4.0","0.5.0","0.6.0","0.7.0","0.7.1","0.7.2","0.7.3","0.7.4"]

Thank you!

**Comment by monkpow** [comment]
@ufologby Could you provide more info about your environment?   nvm, npm and node versions and os?

i get
```
npm install  express-http-proxy@1.0.4
/private/tmp
└─┬ express-http-proxy@1.0.4 
  ├─┬ debug@2.6.8 
  │ └── ms@2.0.0 
  ├── es6-promise@3.3.1 
  ├─┬ raw-body@2.2.0 
  │ ├── bytes@2.4.0 
  │ ├── iconv-lite@0.4.15 
  │ └── unpipe@1.0.0 
  └─┬ winston@2.3.1 
    ├── async@1.0.0 
    ├── colors@1.0.3 
    ├── cycle@1.0.3 
    ├── eyes@0.1.8 
    ├── isstream@0.1.2 
    └── stack-trace@0.0.10 
```

**Comment by ufologby** [comment]
Hi, @monkpow! 
Problem was while executing npm install with --production key like this:
npm install --production express-http-proxy@1.0.4

**Comment by monkpow** [comment]
```
npm install --production express-http-proxy@1.0.4
/private/tmp
└─┬ express-http-proxy@1.0.4 
  ├─┬ debug@2.6.8 
  │ └── ms@2.0.0 
  ├── es6-promise@3.3.1 
  ├─┬ raw-body@2.2.0 
  │ ├── bytes@2.4.0 
  │ ├── iconv-lite@0.4.15 
  │ └── unpipe@1.0.0 
  └─┬ winston@2.3.1 
    ├── async@1.0.0 
    ├── colors@1.0.3 
    ├── cycle@1.0.3 
    ├── eyes@0.1.8 
    ├── isstream@0.1.2 
    └── stack-trace@0.0.10 

```

**Comment by monkpow** [comment]
@ufologby Are you still experiencing this issue?

**Comment by BrandonZacharie** [comment]
Many of us rely on the github release page and git tags for information about what and when code was released . Can you please update them?

**Comment by monkpow** [comment]
@BrandonZacharie Hey, thanks for calling this out. 
I think I fixed this, would you please verify, or let me know what I'm missing.
Thanks,
Nik

**Comment by BrandonZacharie** [comment]
@monkpow LGTM but I do see 1.0.7 as the latest release while NPM only has 1.0.6
