### ISSUE TITLE
how to catch error

### ISSUE THREAD

**Issue by yaoyw0727** [villadora/express-http-proxy#247]
In my project I need to catch error event, but I dont know how to do it?
For example, my proxy config like:
app.use('/proxy', express_proxy('http://127.0.0.1:8087', {
        reqAsBuffer: true,
        reqBodyEncoding: null,
        parseReqBody: false
}

When http://127.0.0.1:8087 is down, then how can I catch the event? I checked the doc many times but got nothing. Does anyone knows? Is there any event callbacks such as onError supported?

**Comment by monkpow** [comment]
see this:  https://github.com/villadora/express-http-proxy#timeout

My expectation from your description is that the server at ```http://127.0.0.1:8087``` is hanging, and not returning a 500 or 404.    

To handle this case, you'll need to spec your timeout with the proxy definition.

I'll update the docs as to what to expect with various error conditions.

**Comment by monkpow** [comment]
https://github.com/villadora/express-http-proxy/pull/252/files

hopefully that helps, let me know if you need anything else.

**Comment by yaoyw0727** [comment]
@monkpow 
Thanks a lot for your response firstly. The option timeout is useful of course.  
After set option 'timeout' for proxy, the response changed to be 504 Gateway Timeout when the server http://127.0.0.1:8087 is down. 
![image](https://user-images.githubusercontent.com/27849864/27999881-4de9ddca-6554-11e7-9fe6-0aee39cb9ed2.png)

And I think I need your help again for another question. Below is the detail description.
In this situation( when http://127.0.0.1:8087 is down or hanging), I want to do something(such as send a notification or record a log), how can?
I tried userResDecorator, but confirmed that this option works well only when recieved response from proxy server. 

So my question is: If I want to send a notifiction or record a log when proxy server is hanging or cannot gave a response, how can?

**Comment by ankibalyan** [comment]
@monkpow @yaoyw0727  How can I alter the error response on timeout or proxy server is down?
