### ISSUE TITLE
How to "next" (skip middleware) based on the response?

### ISSUE THREAD

**Issue by gajus** [villadora/express-http-proxy#248]
I have a setup such as:

```js
app.use('/', proxy(PRERENDERED_APP_URL));
app.use('/', proxy(APP_URL));

```

If `PRERENDERED_APP_URL` responds with an error (e.g. status 404), I want to delegate the request to the next route. I do not see "next" as an option in the `userResDecorator`.

**Comment by monkpow** [comment]
Currently, you'd have to hack something unexpected;   that use case is not explicitly supported, but let me look into it.  This makes sense as a feature.

**Comment by gajus** [comment]
Worth keeping an eye on https://github.com/chimurai/http-proxy-middleware/issues/179

**Comment by monkpow** [comment]
I roughed in a small feature to master today.  Let me know if this matches your expectations/use case.

Thanks for the tip on chimurai!
