### ISSUE TITLE
maybeSkipToNextHandler is already available?

### ISSUE THREAD

**Issue by icaroponce** [villadora/express-http-proxy#257]
Hi, I'm trying to test the new and useful `maybeSkipToNextHandler` option method in one of my use cases, but I couldn't find it on the latest release (`1.0.5`, if I'm not wrong).  Since it's describe as "`experimental`" in the docs, does it mean it's not available in the latest release? If yes, do you have already a predefined "deadline date" to include it into a new release?

**Comment by monkpow** [comment]
Its only on the master branch and hasn't been published to npmjs yet.    I expect to publish a new patch version in the next week with this feature.

**Comment by icaroponce** [comment]
Got it, thank you!
