### ISSUE TITLE
options.preserveHostHdr not working

### ISSUE THREAD

**Issue by erikverheij** [villadora/express-http-proxy#258]
Hi! Thanks for this great library. I tried to upgrade from `v0.11.0` to `v1.0.5`. In my case the proxy does not work anymore. I encountered that the `preserveHostHdr` does not work anymore.

```
app.use(proxy('127.0.0.1:8001', {
  preserveHostHdr: true,
}));
```
this worked fine in `v0.11.0`.

I noticed that `requestOptions.create` is invoked with 4 arguments in [app/steps/buildProxyReq.js](https://github.com/villadora/express-http-proxy/blob/58c09c4d7d3097513538b3b81806f9d6dbedb37d/app/steps/buildProxyReq.js#L13). But I think that method only accepts 3 params, see [requestOptions.js](https://github.com/villadora/express-http-proxy/blob/738442385b51a545d224a4c0c6180b2704a45ec9/lib/requestOptions.js#L67).

**Comment by monkpow** [comment]
Thanks for this.   I'll take a look right now.

**Comment by monkpow** [comment]
I'll cut a release today to publish this.  LMK additional questions.  Thanks again.

**Comment by erikverheij** [comment]
wow that's fast, thx! 👍
