### ISSUE TITLE
Possible to ignore certificate errors?

### ISSUE THREAD

**Issue by thrinno** [villadora/express-http-proxy#270]
On a server I am running two express applications: a static server and an API server. I am proxying requests from the static server to the API server via this package. The API server is running on https and should be also available externally. The certificate is valid as seen from outside (the domain name corresponds to the contents of the certificate), but when proxying internally (i.e. to a localhost:xxxx url) from the web server to the API server, the proxy fails due to invalid certificate.

Is it possible to ignore certificate errors (e.g. similar to -k flag in CURL or the rejectUnauthorized: false in the npm request package)?

**Comment by monkpow** [comment]
No, today the library doesn't, and I don't have plans to support this.   What I've seen others do is use decorateProxyReq to add a cert to the proxy request.

HTH
