### ISSUE TITLE
[maybe] Add a new hook ```decorateUserHeaders``` (or similar name) that is passed details of the proxied request.

### ISSUE THREAD

**Issue by jehon** [villadora/express-http-proxy#280]
Hello,

I am trying to add a header to the response, to tell to the client to wich server the response was proxied.

The idea is that the remote host is dynamically generated from URL: 
```
	app.use('/', proxy((req) => {
			let path = req.originalUrl;
                        ...
        });

```
I use the userResDecorator system:
```
	userResDecorator: (proxyRes, proxyResData, userReq, userRes) => {
		userRes.set('x-epc-forwarded', proxyRes.socket._host);
                return proxyResData;
        }
```

I don't think it is a good idea to use "_host", as it is certainly an internal field.

But more than that, this does not give me the "port" to which the request was made, neither the final path...

Is there a clean way to have the full url to which the request was forwarded? host + port would already be good...

Thanks in advance
Jean

**Comment by monkpow** [comment]
Right now, there is not an obvious way to do this in the library.     In this case, I would expect the server responding to a dynamically generated URL to add the required header.

There is a hook for adding headers to the response (copyProxyResHeadersToUserRes) , but its currently not overridable.   I'd accept a patch for this if you are interested in adding this feature.

**Comment by monkpow** [comment]
@jehon closing this with  7387986 => [#272] Workflow step for modifying headers. (#287) userResHeaderDecorator

LMK how this works out for you.  Thanks for raising the issue.

**Comment by jehon** [comment]
It helps !
Thanks you !
