### ISSUE TITLE
Error when using intercept function

### ISSUE THREAD

**Issue by omerts** [villadora/express-http-proxy#29]
I am getting the following error when intercepting the data, using the intercept function:
```
 Error: Can't set headers after they are sent.
```

**Comment by mfowlewebs** [comment]
Can you provide more information on this error? Or a reproducible test case, ideally?

The two places where express-http-proxy does set headers are both guarded by explicit checks to prevent exactly this kind of error: see [this](https://github.com/villadora/express-http-proxy/blob/master/index.js#L137) and [this](https://github.com/villadora/express-http-proxy/blob/master/index.js#L157).

I'm intercepting just fine in [my trivial test case](https://github.com/mfowlewebs/http-proxy/blob/master/server.js#L37) without problem. I'm skeptical that it's http-proxy generating this error: it's probably something you try and do *after* doing an intercept.

If you are trying to mix external content with proxied content, [the third is a `sent` argument to the intercept callback](https://github.com/villadora/express-http-proxy/blob/master/index.js#L143) provides some interesting capabilities, but that's a very niche use case.

**Comment by creactiviti** [comment]
I get the same error. I assume Handlebars is interfering with the response. 

```Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:335:11)
    at ServerResponse.header (/Users/arik/git/genie-admin/node_modules/express/lib/response.js:718:10)
    at ServerResponse.send (/Users/arik/git/genie-admin/node_modules/express/lib/response.js:163:12)
    at done (/Users/arik/git/genie-admin/node_modules/express/lib/response.js:957:10)
    at _stackRenderer (/Users/arik/git/genie-admin/node_modules/express-hbs/lib/hbs.js:524:9)
    at /Users/arik/git/genie-admin/node_modules/express-hbs/lib/hbs.js:501:7
    at Function.Waiter.done (/Users/arik/git/genie-admin/node_modules/express-hbs/lib/async.js:68:12)
    at renderTemplate (/Users/arik/git/genie-admin/node_modules/express-hbs/lib/hbs.js:492:11)
    at _stackRenderer (/Users/arik/git/genie-admin/node_modules/express-hbs/lib/hbs.js:522:9)
    at /Users/arik/git/genie-admin/node_modules/express-hbs/lib/hbs.js:501:7```

**Comment by creactiviti** [comment]
To answer my own question, this seems to work:

```javascript
app.use('/export', function(_req,_res,next) {
  proxy(config.api.host, {
    forwardPath: function(req, res) {
	  return '/api/jobs';
    },
    intercept: function(rsp, data, req, res, callback) {
      data = JSON.parse(data.toString('utf8'));
      callback(null, data);
    },
    decorateRequest: function(req) {
      req.headers[ 'Accept-Encoding' ] = 'utf8';
      req.method = 'GET';
      return req;
    }
  })(_req,_res,function(){});
});

**Comment by monkpow** [comment]
I believe this issue was in each of your local cases.  Closing now, but feel free to reopen if you'd like to continue the conversation.
