### ISSUE TITLE
How to proxy to a docker container from a docker container

### ISSUE THREAD

**Issue by PrinceDavis** [villadora/express-http-proxy#293]
I am trying to proxy request (ws & http) from a docker container to other containers but its not working.

I am getting the following error

Error: connect EINVAL 0.0.35.40:80 - Local (0.0.0.0:0)
    at Object._errnoException (util.js:1026:11)
    at _exceptionWithHostPort (util.js:1049:20)
    at internalConnect (net.js:962:16)
    at GetAddrInfoReqWrap.emitLookup [as callback] (net.js:1098:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:100:10)

My code is:
const http = require('http')
const app = require('./server')
const config = require('./../config')
const httpProxy = require('http-proxy')
const proxy = httpProxy.createProxyServer({})

const server = http.createServer(app.callback())

server.on('upgrade', (req, socket, head) => {
  proxy.ws(req, socket, head, { target: config.REALTIME_SERVICE_HOST }) //realtime:9000
})

server.listen(config.PORT, () =>
  console.log(`server started on port: ${config.PORT}`)
)

**Comment by crisguitar** [comment]
how did you fix this? @PrinceDavis
