### ISSUE TITLE
protocol is not resolved correctly if host is function

### ISSUE THREAD

**Issue by guy-mograbi-at-gigaspaces** [villadora/express-http-proxy#30]
You can easily detect this from the code. 
ishttps is resolved in constructor. 
however if "host" is function, it should be resolved in `handleProxy` just like the hostname - but its not. 

the proxy basically does not allow me to dynamically decide the host and support https at the same time. 

major issue, might have to use some other library.

**Comment by guy-mograbi-at-gigaspaces** [comment]
I suggest to resolve http/https on top of reqOpts.hostname - this should be the single source of truth.

**Comment by guy-mograbi-at-gigaspaces** [comment]
I will have to drop this library very soon if I don't get a response. 
This is quite a big issue.

**Comment by monkpow** [comment]
@guy-mograbi-at-gigaspaces This looks like it has been resolved for a time.   I added a test here (```0cc6a38```) to replicate the case as I understand it.

Closing this ticket for now, lmk if you are still experiencing issues.
