### ISSUE TITLE
Use userResDecorator in case of error

### ISSUE THREAD

**Issue by valorize** [villadora/express-http-proxy#309]
Hello, I would like to respond with a json response when the server which I'm referring to is offline (`Error: connect ECONNREFUSED 127.0.0.1:8080`). I tried to use the userResDecorator for that. But it seems the function is not called when the request is rejected.
Should I use another approach to handle offline servers?

**Comment by monkpow** [comment]
This connection error should be returned to you (next is called with the connection error as the argument err) so you can process it with an additional handler.      

Perhaps you'd have something like:
```
app.use(err, req, res, next) {
   if (err.code === 'ECONNREFUSED'  && otherRelevantConditions ) {
        res.json({ data })
   }
}
```

**Comment by valorize** [comment]
Thank you for your response. I ended up with:
```app.use('/api', function(err, req, res, next) {
  console.log("error handler", err);
  if (err.code === 'ECONNREFUSED' ) {
    res.status(500).json({ ...: err.message } });
    next();
  }
  else {
    next(err);
  }
});```
