### ISSUE TITLE
Peculiar responses when using userResDecorator?

### ISSUE THREAD

**Issue by mauritslamers** [villadora/express-http-proxy#312]
When using the userResDecorator function, I have trouble with proxying binary files, such as mp3, wave and PDF. 
I am using the userResDecorator as proxied HTML files need a bit of url editing to work properly inside the client app which requests them. 

Because the rest of the application runs fully through websockets and I only want to provide the proxy to authenticated users, I am using the filter function to detect either a cookie set on the userResponse, or for the first request checking for a session key parameter (called socketId here) sent by the client.

This works perfectly for HTML files, but when I am trying to link to binary files of any kind, things go wrong. Of any PDF I only seem receive the first 48 bytes, or the internal PDF viewers of Chrome and Firefox cannot open the data.
Media files, such as MP3 and WAV will often fail in a different way, being that I receive two responses. The first is an empty HTTP 200, then when the proxy has finished the client receives a HTTP 206 (Partial content) response. At the HTTP 200 response, the media player shows, but when the HTTP 206 arrives, the player will gray out as if it received invalid data.

Below is my configuration. I tried to turn on or off any body encoding option, but that didn't help in solving my problem. I tried both Chrome and Firefox. Chrome 65 doesn't download anything, Firefox 58 seems to download the data but then complains it cannot use it. Loading the files directly from the source does work.

I did notice that Firefox consistently gives a bigger amount for the transferred size than the actual size of the file.
If anyone has a clue what might cause my issues it would be great!

```
app.use('/webdav', proxy(myURL, {
    limit: '1gb',
    reqBodyEncoding: null,
    parseReqBody: false,
    proxyReqOptDecorator: function (proxyReqOpts, srcReq) {
      proxyReqOpts.headers['Authorization'] = "Basic AUTH";
      return proxyReqOpts;
    },
  //
    userResHeaderDecorator: function (headers, userReq, userRes, proxyReq, proxyRes) {
      userRes.setHeader('cache-control', ['no-cache', 'no-store', 'must-revalidate']);
      if (userReq.socketId) {
        var existingCookies = proxyRes.req.getHeader('cookie');
        var setCookie = false;
        if (!existingCookies) setCookie = true;
        if (existingCookies) {
          setCookie = !existingCookies.split(";").find(function (c) {
            if (c.indexOf("MeetmeDBSocket") > -1) {
              return c.split("=")[1] === userReq.socketId;
            }
            return false;
          }); // if it finds nothing, setCookie will be true, otherwise it will be false.
        }
        if (setCookie) {
          console.log('found socketId and no valid cookie, setting cookie header...');
          userRes.setHeader('Set-Cookie', "MeetmeDBSocket=" + userReq.socketId + "; MaxAge=3600");
        }
      }
      return headers;
    },
    userResDecorator: function (proxyRes, proxyResData, userReq, userRes) {

      var contentType = userReq.res.get('content-type');
      if (contentType === 'text/html' || contentType.split(";")[0] === 'text/html') { // only edit html stuff
        console.log('editing html to make urls work properly...');
        proxyResData = proxyResData.toString().replace(/(src|href)="\//g, '$1="/webdav/');
      }

      return proxyResData;
    },
    // we remove the query bit
    proxyReqPathResolver: function (req) {
      var returnedUrl = require('url').parse(req.url).pathname;
      // console.log('changing url from ' + req.url + ' to: ', returnedUrl);
      return returnedUrl;
    },
    filter: function (req, res) {
      var socketId = req.query.socket;
      if (!socketId) { // if not present as query, we check in the cookies (follow up requests)
        var cookies = req.get('cookie');
        if (cookies) {
          // it is possible we get more cookies
          var ourCookies = cookies.split(";").filter(function (c) {
            var found = false;
            if (c.indexOf("MeetmeDBSocket") > -1) {
              var id = c.split("=")[1];
              found = !!scServer.clients[id];
            }
            return found;
          });
          if (ourCookies && ourCookies.length) {
            socketId = ourCookies[0].split("=")[1];
          }
        }
      }
      if (!socketId) return false;
      var valid = scServer.clients[socketId] && scServer.clients[socketId].authState === 'authenticated';
      if (valid) req.socketId = socketId;
      return valid;
    }
  }));
```

**Comment by mauritslamers** [comment]
I tried to bring it down to an simpler configuration, and I still have issues:

```
  app.use('/webdav', proxy('https://my.host.ext', {
    limit: '1gb',
    reqBodyEncoding: null,
    parseReqBody: false,
    reqAsBuffer: true,
    proxyReqOptDecorator: function (proxyReqOpts, srcReq) {
      proxyReqOpts.headers['Authorization'] = "Basic myauth";
      return proxyReqOpts;
    },
  }))
```

Whatever I do, the data gets corrupted when the link refers to a binary file, for example an MP3 or PDF. Chrome claims it cannot load the PDF. An MP3 will cause a greyed out player.

**Comment by mauritslamers** [comment]
Closing this issue as my problems were caused by something completely else. Sorry for the trouble!

**Comment by cdsbarreraBooklick** [comment]
Hi @mauritslamers , What were the issue? I am experiencing a similar situation.

**Comment by cdsbarreraBooklick** [comment]
It was a mistake in the certificate for https, Thank you @mauritslamers
