### ISSUE TITLE
Unified way to handle technical errors

### ISSUE THREAD

**Issue by astik** [villadora/express-http-proxy#317]
Hi,
Here is a "enhancement" proposal.

Modified into https://github.com/villadora/express-http-proxy/commit/63b981e0b0, we can find in app/steps/decorateProxyErrors :

```
+function connectionResetHandler(err, res) {
+  if (err && err.code === 'ECONNRESET') {
+    debug('Error: Connection reset due to timeout.');
+    res.setHeader('X-Timout-Reason', 'express-http-proxy reset the request.');
+    res.writeHead(504, {'Content-Type': 'text/plain'});
+    res.end();
+  }
+}
+
+function handleProxyErrors(err, res, next) {
+  switch (err && err.code) {
+    case 'ECONNRESET':  { return connectionResetHandler(err, res); }
+    default:            { next(err); }
+  }
+}
```

The code handle the error and write directly into the response.

From https://github.com/villadora/express-http-proxy/issues/309, another way of managing error is proposed :

```
app.use('/endpoint', function(err, req, res, next) {
  console.log("error handler", err);
  if (err.code === 'ECONNREFUSED' ) {
    res.status(500).json({ ...: err.message } });
    next();
  }
  else {
    next(err);
  }
});
```

So, there are 2 ways to handle 2 errors (ECONNRESET, ECONNREFUSED).
I'd love to have a unified way to handle error and also, i don't want to expose the fact that i will be using express-http-proxy in the header.

So i'd like to handle both error with a custom error middleware with something like this :

```
function genericErrorMiddleware(err, req, res, next) {
  console.log("error handler", err);
  if (err.code === 'ECONNREFUSED' ) {
    res.status(500).json({ error: 'error.proxy' } });
    next();
  }
  else if (err.code === 'ECONNRESET' ) {
    res.status(504).json({ error: 'error.proxy' } });
    next();
  }
  else {
    next(err);
  }
}
app.use('/endpoint', genericErrorMiddleware);
```

I though i could create a userResDecorator to override the built-in behavior, but it does not work (and i don't want to disable streaming anyway).

Maybe we can have an option flag to disable default error handling, allowing error to be forward to next without processing, so that it will rise out of the library's code and into developer's code.
Then we manage with our custom error middleware : genericErrorMiddleware.

What do you think ?

**Comment by monkpow** [comment]
@astik Thank you for the thoughtful analysis, and I like the outcome you've proposed.   

This feels correct to me:
* error shoul be forward to next without processing, so that it will rise out of the library's code and into developer's code.
* allow authors to opt-in to this behavior (because of legacy expectations)

**Comment by monkpow** [comment]
@astik I think this is sorted.   Hope this helps, and thanks for bringing it to my attention.

**Comment by astik** [comment]
Sounds perfect.

In the meantime, sorry to not have done anything on the code and let you do all the work ='(

**Comment by astik** [comment]
After trying to stick the new version in my code, new problems arose (stil, express-http-proxy works as expected =P).
Following #336, i'm trying to have a unified error handling at the highest level.
With the solution you propose in the latest release, error is managed at proxy instance level, not at express level. 
It would be great to have a way for the error code to get out of express-http proxy pipeline in order to be handled by the highest possible level in regular express pipeline.
