### ISSUE TITLE
proxyReqPathResolver not intercepting as intended.

### ISSUE THREAD

**Issue by anderslatif** [villadora/express-http-proxy#318]
By looking at the documentation for proxyReqPathResolver it seems that you can specify some random proxy link (localhost) and use proxyReqPathResolver to intercept and return a modified link (google.com). 

One would think that once the Promise has been resolved then the method will proxy to google. 

This does not happen. It proxies to whatever is defined in the first parameter of proxy() and proxyReqPathResolver has no effect. 

I would like to use proxyReqPathResolver to dynamically define a new URL with a different port. Is this not possible?

**Comment by xFloooo** [comment]
@anderslatif it only works like this
```javascript
     proxyReqPathResolver: function(req) {
         return require("url").parse("/api" + req.url).path;
     },
```

**Comment by anderslatif** [comment]
@xFloooo 

Let's look at this example in the documentation just below your example:

```app.use('/proxy', proxy('localhost:12345', {
  proxyReqPathResolver: function(req) {
    return new Promise(function (resolve, reject) {
      setTimeout(function () {   // simulate async
        var resolvedPathValue = "http://google.com";
        resolve(resolvedPathValue);
      }, 200);
    });
  }
}));```

If the server is set to listen on port 3000 like this:

```app.listen(3000 [...]```

Then the method above does NOT go to localhost:12345 and it does NOT go to http://google.com. It just redirects to the front page of the server at port 3000 without doing any proxying. 

This seems like an error. Why include a method in the documentation that does not work? What purpose does the code above have in a proxy module if it cannot proxy? I recommend that you test it out.

**Comment by xFloooo** [comment]
@anderslatif 
test example...

```javascript
const appSetProxy = app => {
    app.use(
        "/api",
        proxy(`${config.get("API_HOST")}`, {
            proxyReqPathResolver: function(req) {
                return new Promise(function (resolve, reject) {
                    setTimeout(function () {   // simulate async
                        let resolvedPathValue = `http://google.com`
                        resolve(resolvedPathValue);
                    }, 200);
                });
            }
        })
    );
};
```

Turn on debugging `DEBUG=express-http-proxy` . Next, I'm sending a POST - request to /api/orders.
And everything works...

Example debugging log of this query
```trace
  express-http-proxy proxy request options: { headers:
   { origin: 'http://localhost',
     'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36',
     'content-type': 'application/json',
     accept: '*/*',
     referer: 'http://localhost',
     'accept-encoding': 'gzip, deflate, br',
     'accept-language': 'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7',
     connection: 'close' },
  method: 'POST',
  path: '/orders',
  params: {} } +5s
  express-http-proxy resolved proxy path: http://google.com +5s
```

**Comment by anderslatif** [comment]
@xFloooo 

Thanks for taking a look at this. 

I am following the syntax as in the tutorial since wrapping it in a const and saving the API_ROUTE in a config file doesn't help my use case.

So, here's what happens (like it did when I first opened this topic a while ago. I forgot it when I replied).. it goes to localhost:12345 which is just a temp address. It does not substitute the temp address with the resolvedPathValue at all. Again, if this is as intended functionality of proxyReqPathResolver then what is the purpose of resolving with a google link? What is the example code even symbolizing if we can't access the resolvedPathValue afterwards?

A bit more about my use case. I have created a dashboard with different users on my server. Clicking on them sends you to 

```javascript
app.use("proxy/:username" [...] 
```

Then I hope to intercept it so I can use req.params to look up their port and resolve with something like localhost:3000 instead of the temp first parameter of the proxy method that I wrote. 

Here is the debug log. Ignore the ECONNREFUSED on port 12345 error. I was hoping that it tries to resolve with the resolved path instead of the first parameter. It says resolved path http://google.com but that's not where my browser takes me. It also says +0ms when the timeout is 200ms: 

```
  express-http-proxy proxy request options: { headers:
   { 'user-agent': 'Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0',
     accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
     'accept-language': 'en-US,en;q=0.5',
     'accept-encoding': 'gzip, deflate',
     'upgrade-insecure-requests': '1',
     connection: 'close' },
  method: 'GET',
  path: '/',
  params: {} } +0ms
  express-http-proxy resolved proxy path: http://google.com +0ms
Error: connect ECONNREFUSED 127.0.0.1:12345
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1189:14)
```

**Comment by monkpow** [comment]
@anderslatif @xFloooo The documentation is dead wrong.   I'm sorry for creating this confusion.   In this library, the path represents the portion of the url *after* the host.     This documentation shows that you can alter the *host* with the ```proxyReqPathResolver``` method, and that is incorrect.

Rather, the *host* is resolved via the first argument, and not in the options.


e.g.

```
app.use('/proxy', proxy(hostStringOrHostResolverFunction, {
  proxyReqPathResolver:  pathResolverFunction
}));
```

Apologies for the sloppy work on the docs here, and thank you for pointing it out.   

I'll update the docs and try to move this to release asap.

**Comment by monkpow** [comment]
@anderslatif I've updated the docs with the following.   Would love your read on if this is clear and helpful


```
+### Host
 
+The first positional argument is for the proxy host;  in many cases you will use a static string here, eg.
 
+```
+app.use('/', proxy('http://google.com'))
+```
+
+However, this argument can also be a function, and that function can be
+memoized or computed on each request, based on the setting of
+```memoizeHost```.
+
+```
+function selectProxyHost() {
+  return (new Date() % 2) ? 'http://google.com' : 'http://altavista,com';
+}
+
+app.use('/', proxy(selectProxyHost);
+```
 
 ### Options
 
 #### proxyReqPathResolver (supports Promises)
 
+Note: In ```express-http-proxy```, the ```path``` is considered the portion of
+the url after the host, and including all query params.  E.g. for the URL
+```http://smoogle.com/search/path?q=123```; the path is
+```/search/path?q=123```.
+
 Provide a proxyReqPathResolver function if you'd like to
 operate on the path before issuing the proxy request.  Use a Promise for async
 operations.
@@ -79,7 +101,8 @@ app.use('/proxy', proxy('localhost:12345', {
   proxyReqPathResolver: function(req) {
     return new Promise(function (resolve, reject) {
       setTimeout(function () {   // simulate async
-        var resolvedPathValue = "http://google.com";
+        // in this case I expect a request to /proxy => localhost:12345/a/different/path
+        var resolvedPathValue = "/a/different/path";
         resolve(resolvedPathValue);
       }, 200);
     });
```

**Comment by anderslatif** [comment]
@monkpow 

First of all, thank you for confirming to me that the documentation is wrong. I'm relieved.

Your addition to the documentation is good. I already knew that this was possible. 

Did you understand my use case, though? I have a dashboard where I dynamically access all the running node processes on the server. Depending on what user I've clicked into it calls the app.use on path ("/proxy/:username") then finds the correct port based on the process.  

While the documentation turned out to be incorrect I still think the functionality is desirable. It would be nice to be able to intercept the proxying before it is resolved and dynamically change the host after a lookup.

Can I help in implementing this functionality? What can I do to add this? Do you think this functionality is desired and if not why not?

**Comment by monkpow** [comment]
@anderslatif I need some additional information about how this case is different than the ```selectProxyHost``` function in the example above;    you can have this function evaluate on each request, and its passed the current req object.    It *seems* like this satisfies the case you are describing -- I think you would do the lookup in ```selectProxyHost``` and return the resolved host --- but perhaps because I don't yet understand some part of your problem.    Can you say a little more?

**Comment by anderslatif** [comment]
@monkpow 
I had to find some time to test it. I'm back.

proxyReqPathResolver looks like this: 

``` javascript
proxyReqPathResolver: function(req) {
}
``` 
The function takes the request as the parameter. If I were to do it without proxyReqPathResolver it would look like this:

``` javascript
app.use('proxy/:user', proxy(getProxyUrlFromUser('http:localhost:", req,params.user)));
```

This will of course fail cause req is not defined. I can only know the port number after having looked it up by getting the username first.

Does it clear up the use case? It's not important for me to solve this anymore but now I'm in it for the fun of reaching a solution.

**Comment by dbauszus-glx** [comment]
Has this ever been resolved? I have a similar problem where I need to provide proxies to different services via a proxy endpoint. The proxy url including domain is provided in the request.

**Comment by dbauszus-glx** [comment]
Request maybe like `myservice.com/proxy?url=https://mapbox.com/getdata?key=mapbox` or  `myservice.com/proxy?url=https://google.com/getdata?key=google`

The proxyReqPath resolver will replace the key with an access token stored as an environment variable in the middleware. This works for one domain but I cannot get to set the domain itself from request query parameter.

```
const proxy = require('express-http-proxy');

app.use(`${process.env.DIR || ''}/api/proxy/request`, proxy('https://api.mapbox.com', {
    proxyReqPathResolver: function (req) {
        return new Promise(function (resolve, reject) {

        const uri = decodeURIComponent(req.url.split('uri=').pop().split('&token=').shift().split('&provider=').shift())

        const test = `${uri}${process.env[`KEY_${req.query.provider.toUpperCase()}`]}`;

        resolve(test);
        })
    }
}));
```
