### ISSUE TITLE
`getRawBody` 's callback function not be invoked

### ISSUE THREAD

**Issue by JuoCode** [villadora/express-http-proxy#32]
After the breakpoint debugging i found this issue, I'm not sure this is caused by `raw-body` or `express-http-proxy`, because i don't understand [this line](https://github.com/stream-utils/raw-body/blob/1.1.6/index.js#L79)(source code of `raw-body`)

**Comment by bryanfriedman** [comment]
Having the same problem here - requests hang on POST/PUT/PATCH when there is a request body. Any chance this will be fixed?

**Comment by muymoo** [comment]
@bryanfriedman Take a look at the referenced pull request #36.

**Comment by pgraham** [comment]
The referenced pull request will stop the hand but in some cases will not properly pass along the body. If the body has been parsed as JSON it will be an object and so will not have a length property, meaning the content-length header won't be sent and the body itself will not get sent.

A simple fix is to `JSON.stringify(bodyContent)` if it's an object, but I don't think it's right to always assume that an object body means it's JSON.

**Comment by monkpow** [comment]
@pgraham @muymoo @bryanfriedman I believe this is resolved on master now.   I'll let it bake for a few days before publishing to npm.    Feel free to re-open if you want to continue the discussion.
