### ISSUE TITLE
Get 404 error when sending http request to express server form react app

### ISSUE THREAD

**Issue by Nina0408** [villadora/express-http-proxy#323]
Hi There,

My situation is:
1. React APP created by create-react-app, running on port 3000
2. express nodejs api service server, running on port 3001.
3. adding the proxy in express as below:
`const proxy = require('express-http-proxy')`
` app.use('/', proxy('http://localhost:3000'))`

so I will use http://localhost:3001 in the browser to visit react app pages.

The issue is:
The react app needs to call API services in express server, such as 
`  $.get('/api/loadsystems')`

In firebug, I can see the http request url is 
`http://localhost:3001/api/loadsystems`

then I will get 404 error.

I think the express-http-proxy will proxy it to port 3000.

below is the express-http-proxy debug trace I have got from console:
`[1] 2018-03-07T07:22:51.128Z express-http-proxy [start proxy] /api/loadsystems`
`[1] 2018-03-07T07:22:51.128Z express-http-proxy { limit: '1mb',`
`[1] 2018-03-07T07:22:51.129Z express-http-proxy proxy request options: { headers:`
`[1] 2018-03-07T07:22:51.129Z express-http-proxy resolved proxy path: /api/loadsystems`

Please help how to fix this 404 error. thanks very much!!

**Comment by monkpow** [comment]
@Nina0408 I think I need more information to be helpful.   I would often be looking for misconfiguration or expectations in this kind of case.   

It looks to me from your log output that ```express-http-proxy``` is picking up the request, and appears to grok the path.   My first step would be to look at the logs for your server running on app on port 3000 to understand why it is returning 404 for this request.    

Its most likely that ```express-http-proxy``` is behaving as expected;  when you make request, it proxys it to your server on :3000;  when your server on :3000 returns 404, ```express-http-proxy``` returns 404 to your client.

Hope this helps.

**Comment by monkpow** [comment]
I'm going to mark this closed, but feel free to re-open and continue the conversation.

**Comment by zhangzs000** [comment]
you can try to use
app.get('/', proxy('http://localhost:3000'))
or
app.all('/', proxy('http://localhost:3000'))
