### ISSUE TITLE
Using skipToNextHandlerFilter to true still triggers the express-http-proxy pipeline

### ISSUE THREAD

**Issue by astik** [villadora/express-http-proxy#336]
Hi,
i'm not sure if how understand correctly how skipToNextHandlerFilter works. But here is what i think about it :

- if set to false (default behavior) : express-http-proxy pipeline is triggered (copyProxyResHeadersToUserRes, then decorateUserResHeaders, then ...)
- if set to true : express-http-proxy pipeline should be interrupted, regular express pipeline should be triggered

As every express-http-proxy steps are wrapped inside a promise, even if you set skipToNextHandlerFilter to true, express-http-proxy pipeline will be triggered, but after the regular express pipeline.

in my case, the regular express pipeline fully handle the request, i'm not managing any more container. But, problem is when the express-http-proxy pipeline kicks back in, the next step (copyProxyResHeadersToUserRes) expect a container and we have this error :

```
TypeError: Cannot read property 'user' of undefined
    at /my/project/node_modules/express-http-proxy/app/steps/copyProxyResHeadersToUserRes.js:5:24
    at Promise (<anonymous>)
    at copyProxyResHeadersToUserRes (/my/project/node_modules/express-http-proxy/app/steps/copyProxyResHeadersToUserRes.js:4:10)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
```

Should "skipToNextHandlerFilter to true" be terminal (from an express-http-proxy pipeline point of view) ?

**Comment by astik** [comment]
Also, on another note, when using "skipToNextHandlerFilter to true", we go back to the regular express pipeline but we lose all the context from express-http-proxy. For example, we lose the proxy response error code which can be very useful to have a fine error handling.

**Comment by monkpow** [comment]
@astik Thanks for reporting this issue.    I'll look into it this week, but how you've described it sounds correct, and I believe there is likely a bug here.

**Comment by monkpow** [comment]
#361 fixed here
