### ISSUE TITLE
request url parsed error

### ISSUE THREAD

**Issue by wangerniu** [villadora/express-http-proxy#342]
hi, i face such problem when mock data by express-http-proxy in my express app.

for example.
my mock url is `www.data-mock.com/user/5kvKxctecc00208a0?url=`

```
const proxy = require('express-http-proxy');
const express = require('express');
const app = express();
app.use('/api',proxy(morkUrl,{
    proxyReqPathResolver(req){
      return req.path.replace('/api','')
    },
}))

```

my order is proxy request from `/api/user/login` to `www.data-mock.com/user/5kvKxctecc00208a0?url=/api/user/login`. but the params in mock url has been ignored.since, it proxy to 'www.data-mock.com/api/user/login'

that's all .

waiting for your reply.

thx.

version:1.1.0
os:mac

**Comment by monkpow** [comment]
Hi @wangerniu, 

Thank you for this report.
When using `proxyReqPathResolver`, you'll need to construct the whole url, including the query string. 
In this method you have access to `req.url` and `req.params`.

For your case you might have something like:
```
app.use('/api',proxy(morkUrl,{
    proxyReqPathResolver(req){
      // psuedo code
      var query = req.url.split('?')[1];
      return req.path.replace('/api','') + '?' + query
    },
}))
```

**Comment by monkpow** [comment]
see the docs here:
https://github.com/villadora/express-http-proxy#proxyreqpathresolver-supports-promises

Best of luck.

**Comment by monkpow** [comment]
Closing this, feel free to re-open if you want to continue the discussion.

**Comment by wangerniu** [comment]
thanks!
