### ISSUE TITLE
Specify slash is required to match

### ISSUE THREAD

**Issue by NathanielHill** [villadora/express-http-proxy#353]
In setting up proxy routes, I noticed `app.use('/r', proxy(...))` and `app.use('/r/', proxy(...))` seem to behave the same. They both match `/r**`, however I only want the pattern `/r/**` to match. Am I missing a way to specify this without having to create a custom filter function?

**Comment by monkpow** [comment]
the route matcher is express (e.g. `app.use('/r', ...)`, so you'd want to look to express routing to figure out why both patterns are matching.    For what its worth, I'm surprised about this.    Let me know if you figure out anything interesting.
