### ISSUE TITLE
Where to plug in an auth?

### ISSUE THREAD

**Issue by haizaar** [villadora/express-http-proxy#354]
Good day,

I need to implement a custom auth proxy based on tokens that arrive from clients. The auth itself is quite simple - I just need to verify that token exists on the tokens server that runs near by the proxy.

Looking at the documentation, it looks like the way to do it is to pass `filter` function that will do token verification in my case.

Is this an intended use for `filter` function or will it be design abuse? :)

Thank you!

**Comment by dre4success** [comment]
You can always pass the auth as a middleware. Just remember to next() from your auth middleware
```js
app.use('/proxy', auth, proxy(`${url}`, options)
```

**Comment by haizaar** [comment]
Thank you!
