### ISSUE TITLE
FeatureReqeust: Pass the control back to the express server upon success

### ISSUE THREAD

**Issue by siva-vadivel** [villadora/express-http-proxy#361]
When express-http-proxy is used as a middleware and we would like to know certain metrics such as timeTakenForResponse, we would need to be able to pass control back to the express server. 

- Traditionally this is done by calling 'next()' to return control.

**Comment by siva-vadivel** [comment]
userResDecorator is executed right before sending the response to the user, however we would like to pass control bask to express after sending the response. One suggestion would be to call the express's next() method inside userResDecorator, but once next() is called, we would not be able to know when the response was completed (especially in the case of streaming responses)

**Comment by monkpow** [comment]
Ok, @siva-vadivel and @mx781,  thanks for raising the issue, and the discussion.  

See commit above;  I fixed the skipToNextHandler, and added the expressHttpProxy res and req to the user.res so you can read the proxy res and req values.
