### ISSUE TITLE
how to preserve the url?

### ISSUE THREAD

**Issue by lzl124631x** [villadora/express-http-proxy#375]
Example:

```
app.use('/api', proxy(process.env.SERVER_URL));
```
This will redirect request to `/api` to `process.env.SERVER_URL/`, but I want it to be `process.env.SERVER_URL/api`.

**Comment by monkpow** [comment]
This is how the library behaves today.   Take a look at the following for a solution
https://github.com/villadora/express-http-proxy#proxyreqpathresolver-supports-promises

**Comment by monkpow** [comment]
I think this will answer your question.  Feel free to re-open this if you’d like to discuss further.

**Comment by lzl124631x** [comment]
@monkpow Thanks.

Do you know why 
```
app.use('/api', proxy(process.env.SERVER_URL + '/api'));
```
won't work?

The `proxyReqPathResolver` is powerful but not very handy. Maybe we can absorb some easy config pattern from https://webpack.js.org/configuration/dev-server/#devserver-proxy
