### ISSUE TITLE
TypeError: Cannot read property 'user' of undefined

### ISSUE THREAD

**Issue by chrisbutler** [villadora/express-http-proxy#377]
when returning false from `skipToNextHandlerFilter`:

```
skipToNextHandlerFilter: function(proxyRes) {
	return proxyRes.statusCode === 403;
},
```

this is the only function in my `proxy()` call... why is it trying to do something with `.user` trying to call https://github.com/villadora/express-http-proxy/blob/master/app/steps/copyProxyResHeadersToUserRes.js???

**Comment by iamdey** [comment]
same error here.

it looks like it has been fixed in master branch https://github.com/villadora/express-http-proxy/commit/8bac3fe097942cefcb2aaa2066325795257b9cab#diff-9e1003fee59d85fd09e57b0ed288d192

but not yet released

/cc @monkpow

**Comment by monkpow** [comment]
I just published a new version with this fix.     Let me know any questions, thanks.
