### ISSUE TITLE
Posting to a different host with a specific port

### ISSUE THREAD

**Issue by jpierson** [villadora/express-http-proxy#38]
I'm attempting proxy a post to a different host with a specific port number but I'm getting the following error.

>
net.js:927
      throw new RangeError('port should be >= 0 and < 65536: ' + port);
      ^
>
RangeError: port should be >= 0 and < 65536: 3002path1/path2
    at lookupAndConnect (net.js:927:13)
    at Socket.connect (net.js:904:5)
    at Agent.exports.connect.exports.createConnection (net.js:63:35)
    at Agent.createSocket (_http_agent.js:174:16)
    at Agent.addRequest (_http_agent.js:143:23)
    at new ClientRequest (_http_client.js:133:16)
    at Object.exports.request (http.js:31:10)
    at c:\Users\jeff.pierson\Source\ReadyTouch\uk\gmaweb\node_modules\express-http-proxy\index.js:96:50
    at IncomingMessage.onEnd (c:\MYWEBAPPDIR\node_modules\express-http-proxy\node_modules\raw-body\index.js:149:7)
    at IncomingMessage.g (events.js:260:16)

Notice the text `3002path1/path2` which makes it look like the port number is being smashed together with the path when constructing the URL.

**Comment by mfowlewebs** [comment]
Just another library user here- [this use case works fine for me](https://github.com/mfowlewebs/http-proxy/blob/master/server.js#L33). Linked trivial example is a proxy to `localhost:8081`, and works fine. If you believe you still have an issue, you should create a reproducible test case for this ticket.

**Comment by uniqname** [comment]
I ran into a similar problem. This error occurs when attempting to include a path on the end of the proxy host. It isn't immediately clear that the first argument to `proxy` is the target host and that any path a request needs to be forwarded to _must_ only be in the `forwardPath` option.

**Comment by monkpow** [comment]
@uniqname I've tweaked the docs slightly to address hoping to clear up this confusion.

**Comment by monkpow** [comment]
I'm closing these as questions, addressed by documentation.  Let me know any questions.
