### ISSUE TITLE
How to use basic auth?

### ISSUE THREAD

**Issue by georgepaoli** [villadora/express-http-proxy#402]
Hi,

How to use basic authentication i.e. 'user:password' in a proxy?

Like a 'auth' option of https://github.com/nodejitsu/node-http-proxy#options

Thanks.

**Comment by raphaeleidus** [comment]
basic auth just generates an HTTP Header. You should generate the authorization header for your user:password combination and then just insert that.
there are sites like this one that can do it for you: https://www.blitter.se/utils/basic-authentication-header-generator/

**Comment by georgepaoli** [comment]
Thank you @raphaeleidus
