### ISSUE TITLE
How to remove a response header?

### ISSUE THREAD

**Issue by acgpiano** [villadora/express-http-proxy#403]
If I want to remove X-XSS-Protection header, how to do it? I try to remove it from proxyRes but it doesn't work. I don't want to set like X-XSS-Protection: 0, I just want to remove it, thanks!

**Comment by raphaeleidus** [comment]
in my experience you have to actually remove the header from two different objects in order to get it to be removed. Code sample below. 

```javascript
var proxy = require('express-http-proxy');
var app = require('express')();

app.use('/proxy', proxy('www.google.com', {
  userResHeaderDecorator: function(headers, userReq, userRes, proxyReq) {
    delete headers['x-xss-protection']; // remove header from the headers object
    userRes.removeHeader('x-xss-protection'); // remove header from the response object
    return headers
  }
}));

**Comment by acgpiano** [comment]
@raphaeleidus  Thanks a lot! But it doesn't work for me, you can remove these headers just in this object. When the program run into userResDecorator you still can see the header in raw-headers object, not headers, I finally removed it in userResDecorateor and it worked.

**Comment by raphaeleidus** [comment]
Ugh I made a mistake
```
var proxy = require('express-http-proxy');
var app = require('express')();

app.use('/proxy', proxy('www.google.com', {
  userResHeaderDecorator: function(headers, userReq, userRes, proxyReq, proxyRes) {
    delete headers['x-xss-protection']; // remove header from the headers object
    userRes.removeHeader('x-xss-protection'); // remove header from the response object
    proxyRes.removeHeader('x-xss-protection'); // remove header from the proxy response object
    return headers
  }
}));
```

The other this is that my code sample assumes that the proxy is returning the all lowercase version of the header. When you use `.removeHeader` it is case insensitive but the headers object passed to the function is case sensitive

**Comment by acgpiano** [comment]
It's not about case sensitive, I use String.toLowerCase() to handle this but it still not work, if you checkout nodejs original HTTP response, you can see it really removed from headers property, but still in another property named raw-headers. The raw-headers finally returns to the browser. I just don't know why I use removeHeader in userResDecorateor method can work.

**Comment by dalalayan1** [comment]
@acgpiano @raphaeleidus - i tried the same it doesnt work at all.
I want to somehow stop the file download by deleting a header. But I am unable to delete it.

`userResHeaderDecorator(headers, userReq, userRes, proxyReq, proxyRes) {
    console.log("\nRES HEADERS => ", headers);
    userRes.on('data', function(data) {
      // var `data` is a chunk of data from the response body
      console.log("FILE BODY => ", data)
    });
    if(headers['content-disposition']) {
      delete headers['content-disposition'];
      userRes.removeHeader('content-disposition');
      proxyRes.removeHeader('content-disposition');
    }
    return headers;
  }`

**Comment by duolabmeng6** [comment]
```
    userResDecorator: function (proxyRes, proxyResData, userReq, userRes) {
        userRes.removeHeader('content-disposition');
        return proxyResData
    }
```

thank you
