### ISSUE TITLE
Test for https fails if proxy is a function

### ISSUE THREAD

**Issue by dalelotts** [villadora/express-http-proxy#44]
While not in the documentation, the code allows the 'proxy' to be a function or a string - in our case the code is much cleaner (since we don't know the final proxy protocol or url until the request comes in.

However, the check for https does not work properly because the test does not call the function.  

Line 19: ``` var ishttps = /^https/.test(host);```

Delaying the https determination until after the method is called and returns a url would be reasonable.

**Comment by gstroup** [comment]
For now, you can set the 'https' option to true

    app.use('/somepath', expressProxy(getUrlFromSession, {
		https: true,
		forwardPath: function (req) {
			  var forwardPath = url.parse(req.url).path;
			  return forwardPath;
		}
	  }
    ));

**Comment by monkpow** [comment]
@dalelotts It turns out that this specific line of code has been obviated since your question came up.   Can you let me know if you are still having any issues?

**Comment by monkpow** [comment]
@dalelotts See test here 0cc6a3813d5236a22eb819cd24575270465de239.    I believe that the issue you mention is resolved, but please let me know if you continue to have issues.

Closing as resolved.
