### ISSUE TITLE
decorateRequest options

### ISSUE THREAD

**Issue by rorydonohue** [villadora/express-http-proxy#49]
Hi, 

Thanks for the great module! 

I'm trying to use decorateRequest to add an X-Forwarded-For header, so the back-end service has some idea of the original endpoint. It looks like the IP address of the request (req.ip) isn't available as an option in reqOpt:

      var reqOpt = {
        hostname: (typeof host == 'function') ? host(req) : host.toString(),
        port: port,
        headers: hds,
        method: req.method,
        path: path,
        bodyContent: bodyContent,
        params: req.params
      };

Would it be possible to add this in ? Or perhaps there is a better way to set X-Forwarded-For ? 
Thanks!

**Comment by homerjam** [comment]
+1

**Comment by bitdivine** [comment]
Looking at the examples this _should_ work for you, I think:

    decorateRequest: function(req) {
       req.headers['X-Forwarded-For'] = 'one pink penguin';
       return req;
    }

(adapted from one of the examples in https://github.com/villadora/express-http-proxy )

**Comment by dpsthree** [comment]
I have a similar problem. I need access to the session to supply headers on who is requesting information.

**Comment by monkpow** [comment]
The req object is now passed to the decorateRequest method as the second argument.  I've updated the docs in the above pull request.

**Comment by monkpow** [comment]
I believe this issue is now closed.   Please let me know any issues.
