### ISSUE TITLE
Unable to remove default charset from "content-type" response header

### ISSUE THREAD

**Issue by ssafayet** [villadora/express-http-proxy#539]
I am using express-http-proxy to proxy requests to a Next application. The issue is, that express-http-proxy is modifying response header "content-type" that is being set by the Next server and adding a "charset=utf-8" by default. Is there any way to prevent this behavior and pass specific response headers as it is to the client without modifications? It is breaking Next's SPA behavior. 

I think [This file](https://github.com/villadora/express-http-proxy/blob/master/app/steps/copyProxyResHeadersToUserRes.js) is causing behavior particularly this line:

`res.set(item, rsp.headers[item]);
`

Express is setting the charset by default as it seems.

**Comment by monkpow** [comment]
Hi @ssafayet,

Take a look at [this section ](https://github.com/villadora/express-http-proxy?tab=readme-ov-file#reqbodyencoding)in the README. I think this should cover your use case. 

I'm going to close this as answered, but feel free to re-open if you want to continue the conversation.
