### ISSUE TITLE
port passed in proxy(host) string is ignored

### ISSUE THREAD

**Issue by mattnworb** [villadora/express-http-proxy#55]
A custom port value passed to `proxy()` like `proxy('http://localhost:5678')` is completely ignored, even though some layers of the code seem to expect or support this.

[`parseHost`](https://github.com/villadora/express-http-proxy/blob/32849aadefd29ff7bf3992bc5d45ad42c13d8afe/index.js#L228) has logic for returning an object containing a port inside the host string.

However, the exported `proxy()` function [splits apart the passed-in `host` string and overwrites the input `host` with whatever is on the left side of the `host:port`](https://github.com/villadora/express-http-proxy/blob/32849aadefd29ff7bf3992bc5d45ad42c13d8afe/index.js#L32-L34) prior to the point where `parseHost()` is called.

The [port on the right-hand side of the original input is then never read](https://github.com/villadora/express-http-proxy/blob/32849aadefd29ff7bf3992bc5d45ad42c13d8afe/index.js#L39) - the `reqOpt` object gets assigned a field `port: options.port || parsedHost.port`, but since the original input `host` was overwritten after the string splitting, the `parsedHost.port` never contains anything but the default port for the protocol.

This results in a usage like `proxy('http://localhost:8080')` in sending proxied requests to port 80 on localhost, not 8080.

**Comment by krimple** [comment]
I got burned by this - in 0.6.0 it worked fine, but now it's stripping the port.  Found out by running an old sample with the old version baked in.

**Comment by dhwang** [comment]
Fix this please

**Comment by villadora** [comment]
Thank you for pointing out, fixed in 0.7.1.

**Comment by gstroup** [comment]
Thanks for fixing!

**Comment by mattnworb** [comment]
thanks @villadora
