### ISSUE TITLE
how can i proxy https 

### ISSUE THREAD

**Issue by luxueyan** [villadora/express-http-proxy#56]
Can it support https proxy?

**Comment by gstroup** [comment]
Yes, you can use the 'https-proxy-agent' package.  Something like this:

    var corporateProxyServer = process.env.HTTP_PROXY || process.env.http_proxy || process.env.HTTPS_PROXY || process.env.https_proxy;
    if (corporateProxyServer) {
		corporateProxyAgent = new HttpsProxyAgent(corporateProxyServer);
    }

Then inside the `decorateRequest` method, add the agent to the request:

    req.agent = corporateProxyAgent;

**Comment by monkpow** [comment]
I'm going to close this issue.     I've added this Question and Answer to the docs here 96d557372169eaef88e79e4a3f1de29747518b6e

**Comment by pt-br** [comment]
Is there any example of usage with express? @gstroup @monkpow 

I didn't get it :/

**Comment by gstroup** [comment]
```
var proxy = require('express-http-proxy');
var HttpsProxyAgent = require('https-proxy-agent');

var corporateProxyServer = process.env.HTTP_PROXY || process.env.http_proxy || process.env.HTTPS_PROXY || process.env.https_proxy;
if (corporateProxyServer) {
		corporateProxyAgent = new HttpsProxyAgent(corporateProxyServer);
}

function setProxyAgent(req) {
	if (corporateProxyAgent) {
		req.agent = corporateProxyAgent;
	}
	return req;
}

app.use('/proxy-api', proxy('real-api-endpoint.com', {
	forwardPath: function (req) {
		var forwardPath = url.parse(req.url).path;
		return forwardPath;
	},
	decorateRequest: setProxyAgent,
}));
```

**Comment by luxueyan** [comment]
I didn't describe clearly. Our development-env use http, and our prodction-env use https. I need proxy dev apis as '/api/xxxx' to the production https server

**Comment by vtuwei** [comment]
Also interested to know how to proxy from a http server to a https server. @gstroup i wasn't able to make it work using your example.

**Comment by vtuwei** [comment]
@luxueyan did you find a solution?

**Comment by monkpow** [comment]
@luxueyan I've added an option that will allow you to force https on the proxy request.  Hope this helps.

**Comment by luxueyan** [comment]
@monkpow  Thanks very much! I will try this in free time!
