### ISSUE TITLE
Evaluate host() function 

### ISSUE THREAD

**Issue by mvdenk** [villadora/express-http-proxy#80]
Hi guys,

I'm having the following situation over here: based on the incoming request I want to decide to proxy to host x or y. So ideally I want to evaluate the host(req) function every time there is request to my proxy instead of evaluating only the first time.

I've looked into the source code and see multiple solutions. One of them is removing [this](https://github.com/mvdenk/express-http-proxy/blob/master/index.js#L51) line of code (if statement to check if the host is already determined in a previous request), this won't break tests. Instead of removing we can also extend the if statement to make it a little smarter.

I'm curious about your vision on this topic.

**Comment by monkpow** [comment]
Thanks for your comment.   This sounds like a reasonable feature.

My preferred approach would be to have an option like 'memoizeProxyHost: false' (or similar) so that by default, we  'evaluate once', but allow 'evaluate each time'.

I'd accept a patch with tests for this feature if you're inclined.     Otherwise, I'll be happy to pick up when I get to it.

**Comment by TobiasNickel** [comment]
isn't it already possible?
you could make many proxies:
```
    var userService = proxy("userService",{options:values})
    var fileService = proxy("fileService",{options:values})
    var couchDBService = proxy("couchDBService",{options:values}) // rewrite path
    var awesomeService = proxy("awesomeService",{options:values})

app.use(function(req,res,next){
    // you don't need to use switch or an extra function, just some logic to select the proxy. 
    switch(selectServer(req)){
    case "user":userService(req, res, next);break;
    case "file":userService(req, res, next);break;
    case "awesome":awesomeService(req, res, next);break;
    }
})
```

using such a structure, you are ready to build a micro-service architecture.

**Comment by monkpow** [comment]
@mvdenk How does @TobiasNickel's solution work for your case?   For the case example he's shown above, the approach feels all right to me.

If this approach doesn't work/doesn't appeal to you,  would you give a bit more detail about the specific case you are looking to solve?

Thanks

**Comment by monkpow** [comment]
Closing issue as solved (by @TobiasNickel comment).   Feel free to re-open if you'd like to continue the discussion.
