### ISSUE TITLE
querystring.stringify for post data

### ISSUE THREAD

**Issue by TobiasNickel** [villadora/express-http-proxy#81]
I needed to add some code to forward postdata properly. 
after getRawBody the bodyContent is an object. 
maybe because I used the bodyParser middlewhare?
```
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({
    extended: false
}));
```

my solution was changing line 87 to:
```
bodyContent = require('querystring').stringify(reqOpt.bodyContent);
```

but maybe this will only work with body parser. 
if it can be a tring before we can do 
```
bodyContent = typeof bodyContent == 'string' ? bodyContent : require('querystring').stringify(reqOpt.bodyContent);
```

**Comment by monkpow** [comment]
@TobiasNickel This is a fairly common request, but the work we've done to date has not resolved it.   Can you help by posting a gist of the simplest possible failure case?    I will pick this up this week if you can provide the test case.

Thanks!

**Comment by monkpow** [comment]
@TobiasNickel Are interested it testing this to see if it fixes your use case?
