### ISSUE TITLE
Can't intercept html in response body

### ISSUE THREAD

**Issue by topheman** [villadora/express-http-proxy#9]
Hello Villadora,

I can't seem to intercept html in a response body - here is the test case : https://github.com/topheman/express-http-proxy/commit/264e451a0dec59b346da2ddcdd7fa0c93feba8eb

Other use case where intercept doesn't work : https://api.github.com/
Even if it's json returning and I can access data in the intercept callback, but there is an encoding problem (though everything is in utf8).

Tophe

**Comment by mlenkeit** [comment]
I had a similar issue where I couldn't access any data from the response in the intercept hook (also when proxying to Github), yet I saw the response in the browser. It turned out to be a caching-related.
I added this to solve the problem.
```javascript
decorateRequest: function(req) {
  delete req.headers['if-modified-since'];
  delete req.headers['if-none-match'];
  return req;
}
```

**Comment by ebaumqb** [comment]
@villadora I am facing an issue accessing the data when the server returns a 304. How would I handle the intercept if the server returned 304. I don't want to disable the cache.

```intercept: (rsp, data, req, res, callback)=> {
      var data = JSON.parse(data.toString('utf8'));
      callback(null, JSON.stringify(data));
  }```

when the server returns 304 data is undefined.
