### ISSUE TITLE
How to handle 301 redirects?

### ISSUE THREAD

**Issue by pt-br** [villadora/express-http-proxy#91]
Hi @villadora,

I'm having some troubles when trying to proxy a host containing a 301 redirect.

Basically, I'm redirect(as usual) to target's domain, leaving my localhost proxy environment.

You can use as example: http://globo.com

Thank you in advance.

**Comment by pt-br** [comment]
Hi guys, I just solved my own issue.

If you need to follow redirects, just replace the http module for this https://www.npmjs.com/package/follow-redirects

The usage is simple, just put `var http = require('follow-redirects').http;` into index.js and the proxy will follow redirects as well

**Comment by pt-br** [comment]
I'm reopening this bc I think it's a information that should be on the read.me, just not sure about it.

**Comment by marcelpanse** [comment]
Why does this doesn't work on for example https://google.com/ it still redirects my browser to https://google.nl. Is there a way to fix this?

Some context: I'm trying to create a page where people can insert their URL and I'll proxy the content and add some javascript to it on the reponse. For example: http://myservice.com?url=google.com
should show the google page with my javascript added.

**Comment by monkpow** [comment]
When the proxied request is returned to express-http-proxy, you have the opportunity to inspect and modify it.    This feature is called 'intercept', and you can see some syntax info in the README file, and also in the test cases for intercept.    

There's no way that I'm aware of to get google to stop sending you a redirect instruction.
